name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write        # grant write access to the Pages API
  id-token: write     # required by configure-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy site into 'public'
        run: |
          rm -rf public
          mkdir public
          # copy everything, including dotfiles
          cp -r frontend/ipl-analyzer-frontend/. public/

      - name: Disable Jekyll
        run: touch public/.nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
