name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & build
        working-directory: frontend/ipl-analyzer-frontend
        run: |
          npm ci
          npm run build

      - name: Prepare Pages artifact
        run: |
          rm -rf public
          mkdir public
          # Copy the build output
          cp -r frontend/ipl-analyzer-frontend/build/. public/
          # Disable Jekyll processing
          touch public/.nojekyll

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - uses: actions/deploy-pages@v4
