# .github/workflows/pages.yml
name: Deploy frontend to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy site into 'public'
        run: |
          rm -rf public
          mkdir public
          cp -r frontend/ipl-analyzer-frontend/* public/

      - uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - uses: actions/deploy-pages@v1
